data:
  root: "./dataset"
  train_split: "train"
  val_split: "test"
  max_samples: null

training:
  batch_size: 24
  lr: 0.0002
  epochs: 400
  num_workers: 4
  save_interval: 10
  val_interval: 5
  seed: 2023
  val_ratio: 0.1 # 验证数据集使用比例 (0.0-1.0)
  val_visualize: true # 是否在验证时保存可视化结果
  val_vis_samples: 4 # 每次验证保存多少个样本的可视化

model:
  image_size: 512
  num_res: 10
  in_channels: 1
  n_feats: 64
  n_encoder_res: 6
  pixel_unshuffle_factor: 4
  loss_type: "l1"

output:
  out_dir: "./angle_diffusion/output/stage1"
